### ISSUE TITLE
定期実行を組み込む

### ISSUE THREAD

**Issue by matsubara0507** [haskell-jp/antenna#19]
去年 Drone CI で毎時実行を実現したけど、いつぞやから自動実行がされなくなってしまった（今は手動）。
TravicCI にして戻してもいいけど、いっそのこと適当な無料枠インスタンスで cron っぽい動作をさせようかなと。

つまり、あるインスタンスで `antenna --saver sites.yaml` とかやっていれば毎時更新してくれる（コミットしてくれる）ようにするイメージ。

次のステップでやる

- [x] Step 0: CLI ツールのオプションの整理 #20 
- [x] Step 1: CLI にコミットオプションを追加 #21
- [x] Step 2: CLI に定期実行オプションを追加 #22 
- [ ] Step 3: (おまけ) オプションの畳み込み #23
- [x] Step 4: インスタンスを設定する

**Comment by matsubara0507** [comment]
### Step 4: インスタンスを設定する

のメモ

- [x] GCP Console からインスタンス作成
    - f1-micro オレゴン
    - 30GB 標準ストレージ
    - Ubuntu 18.04
- [x] docker インストール
    - https://docs.docker.com/install/linux/docker-ce/ubuntu/ を上から順に
- [x] イメージの pull : `sudo docker pull haskelljp/antenna`
- [x] sshkey の設定
    - 生成 `ssh-keygen -t rsa -b 4096 -C ""`
    -  pub key を haskell-jp/antenna の deploy key に設定する
- [x] クローン
    ```
    git clone git@github.com:haskell-jp/antenna.git
    cd antenna
    git checkout gh-pages
    ```
- [ ] 起動
    ```
    // お試し
    sudo docker run --rm -v `pwd`:/work -v `echo $HOME`/.ssh:/root/.ssh haskelljp/antenna antenna--verbose --with-commit 
    sudo docker run -v `pwd`:/work -v `echo $HOME`/.ssh:/root/.ssh haskelljp/antenna antenna--verbose --with-commit --with-push --with-copy --hourly
    ```

**Comment by matsubara0507** [comment]
定期実行自体は完了したのでクローズ
